sudo: false
language: scala
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/
scala:
- 2.11.6
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -pass pass:$PGP_PASSPHRASE -in secring.gpg.enc -out local.secring.gpg
  -d
- openssl aes-256-cbc -pass pass:$PGP_PASSPHRASE -in pubring.gpg.enc -out local.pubring.gpg
  -d
env:
  global:
  - secure: O5icuS6aJmJAapG4wIwswNX2Gxu7IbxsiSHDwNz4kkoFNyQNENhnSYImU1x8MWL9JP1XrjYsSZkFl8UwTfyTGiumF+rOS0cyIFQcc494dG3Twd0RivCyniLkQEIUvM/CFf+1BxrrSEod0GB1AZn9hdgJCZF+fS7+qriF5FyOh8iUsQlJlN9rqm7AveUNyJzZjeUA1SbzecUDDTXbh+Yg3e3D919Fd/Q/r5YlINFqpsb2VH1ErTRndjgjlEI+OGng0JVHESxdUCir1htJW/VOHwkFyWEM0zehwyFQtOoDxqg7KH+iIyTNEElHGmvW0EljdhNYweHGNqdY6K3UzybO+2JraBAE7rWjq2MeKcx9MsNodYTq0UOl21EpL2uuvSg/MpfnFweJDerp1wKaY/MMUyOoT6BhQGJJU9YT1urQ9g+fKj6jxe540LPzdWeGee29RhFZ2/Sb81MmW4+QbFoPk1LW3FaITkRUEFN0xG9aeGjXSQ/HKsuNSuusiTjIELO7khwiUckhVUjtH6lDL0ds6DsJgVr6usiF+gbIISUOOib6LXqiAZHVwYMN8Ovlp+3orMifiIBx2ygS5lSjpTQqs5hrUl9DVw5dA28kSgo0WSxy7CwzO6ehfQYD/jlcU3998BBBYBlV7dmYWFCIZyRkYA/4qZ1fczRmNJykTdCySI0=
  - secure: fHzLp+8aNBu+08lsvmsufb1O1RC4wq5P6hTyekrrMx863r82FQJ+fVlkGLQdzb+H/PRJHl6aPn8L1sc1ms3A4Amm8siTfg7+nrnhxmQUP7ILxP1bI043a9IKuGw4KvgHxDLtljeJ8ShQSUwoFhq69o4Mf+cdj5pf9CIHIUxswpH319r3aXM4W6YxwjGk/0SZNJsqv4Awk8QHOJ4fIE02BJ75xuS1MYqtQZLo/pVA/V5VF7yDUfUZuMjtkIjUtktzAnrv7GhkHZkuJ38ScIrUV5GU1fq5nUO6M2vYYu7HeceOfKMtsKukXXysFKnihvdP/LrcY4Q7bRKwDLzBg2EFPXEu54Lk+k46Kfvkb1YIOzsi8ss4IF5xnVk/LeX7B3WQoecPW3d6oCJhY7zNg5u72ezXijR7Wu3NGTuH3OodSMmrGMbpoFvr9MkeYXCeAcodFv1sIXuFvHNnZ/6fUL8SRQwMjqYLTZVWbSMqgTPKSWRctYdPI60992klxMY7PTLFTmvuNstBK1Ow/yaXbQhoLftIUPcaiNFYDFxnwesmufTmpPK1Vz6LDyBO34v/crTpAcfktflqrf38Zn0o8ADhRkmrEreoMUbtu2RFsK3zaxrUuA9Dej7y0HWzHHTzNCRy3DCP4pPJKLYXjiarU6Lv0CfbOF5q/Al8eRzQhOLYY3E=
  - secure: hAj/ml1DRjLRIHo6KNhJHj/ppHAbzv3c3o/m5s5CWpx+1J7/ZNNYQ68TPVp5u2WPmZMXxrwqdAuLCQbAPnOaRzmoN1quR3iZUGcZryQksqQKkSRkuocgSYcHiWGbxKUnFt4rzAPMKoaFYPuQXUP3hVh74bdtTKi/ghrKT/A8kXSqQVLPK3EehNUHylYENe6swQmHE6RV402Ev6L19yXc6GPY2akG8wo6+Q2fiugFr61U85f/KOwbsxN9ULFAtjqkikbuxBmuzd5qUT7b/4ZUgDS318s9POG6F4AhIVDOVcgF+fxaEIZqYNFzuAFz4QjHTSsjB7axCHL5IgFk+9B6EOe0oxYuEQhohRtRECijRcKdSGlLkCMcRA1keSBE0MPcVhBBvW4WLp87UXfnOh4Q46oZdWvJFK8qQhRYXq67SUqPzBF/EOtQRKD1qF8xwQTAGCMu1jfq8EJysH7mHuX5F3oyq5Y64FRC3Vs4OSv1yX8pghGhcjt/FMnwpZbtBhClHM4ChccRlbp6IBv79nMWttS8QkDqsj+zzbqYPa0CZiD0z+mc9YbucnjOb+oH3XzQbVqvzo2gZLP6vQJXCDZd4vaos5D6y3daubV2fzKjdPhh0zjiHHWreCw40OogA7CTCFiBSqfVX1BWfbIET+z6+Fqunnw84zKYniRP7TE2GYo=
script:
- ./sbt ++$TRAVIS_SCALA_VERSION compile
- if [ "$TRAVIS_BRANCH" == "master" ]; then ./sbt ++$TRAVIS_SCALA_VERSION publish-signed;
  fi
notifications:
  email:
  - on_success: always
