sudo: false
language: scala
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/
scala:
- 2.11.6
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -pass pass:$BBCPGP_PASSPHRASE -in secring.gpg.enc -out local.secring.gpg -d
- openssl aes-256-cbc -pass pass:$BBCPGP_PASSPHRASE -in pubring.gpg.enc -out local.pubring.gpg -d
env:
  global:
  - secure: QyWwukcUrZIrw3hS8KLtP4ziAcXdmPkzyJCjdKiwWoNEAF4OtC0tIwK4xEeXI8EwbtNmYX5lZiDh5fYLIAMFisvAq1CIqfDG1lr08eExqpP5aOx209khh2CXG/vi1xk0rRPQSzfFRxqcDGUgfeZIgpUa563rcsLX/eBh9C55r2ZNl98h+5nkSVMFHhD2b9Q1ZOus63K5Jl4Ha/FG39hHX2fIKQW7AZtVp3wZ3cr7m6GuI9VTvBrtVeRt2EP2SAUIiCnWoYGpty85qa2IZfSSoXmxBEbcmiB0B7pw7I40SnxK23375lUKwZiMtW/dF9XzxYIeGZq0l/CboY/i7ms2DxIwY5ntHR6ykrZFE3z/o7+fLRpQrIb72EqZwYKqd5imLmJ+gjgwlUfIzZ0/obbHgbaOCVaE0xSHBu4X9Rwgy0J/qdF7WV45WNtx1xC6XgenIgNhxKcR5Qq76XMEu6aX9MlqLllz/gbWFIvizepM0dlHo8/8rX6C3sAiK7X6vdQEhQbL9dvpQSFS9KK15Rb6src3BW5znQ54y9/WL9gYGStliuI4dJhaKfCHqF+GloVq8Wc8ErOT/7zfRO7SVqbHAXblv1kSc105rKAK16+7TbqzwQOUzu3+5vezLtm0vmG5z2RrwAUTYGiZFzFIqGAyAeqomRZVrm92/GPPQTLZFNI=
  - secure: E/UtnEOiudtNtly5q5EPb5EebIV11IfSDLYMCXEUrFY+Lfr9ZfbmJnwg64g3OWmh3AE7DpmYf47Xme4UOTWUBnoUH8mJ6xWuidW/X+gLiXWIm0xh8mJYtTkNFGKbLRqeD+q7o7dvTKo8trK88NBIjhak/zdobB+P/MX20NKxQehqhz3EVijGauX8eERn/aj57j4nEQ8hZfK0Zs2bHf3PxKL21vo9sEW7NGiOJ+InNSVWQJg1GStsjqUX6zeaMDqJTa267hrqhLa1PZpWyN8OyPcnePzZSjhymFwIL63Ugp7rGpORCTwTrW+sf58ARYI+tjevQTKL/tLnlXf+2c9P45KUX2pdBCakfXo2nThmnZNCdJdEDVg//XZ4ImEsf4rbRUQtSQCF902P9P5/menEkJTzj995eMSB9yv9OKwALqUdeU0X3SKUc1YUXJ61ohECVx5rMgN3hhPz11HJuzrpH/lwuezfm/4AecSZKp+xXXC3Fr5GSTIlzH/UIm5w47qo0yXvtj2VreHsoZXTCA6WxU9UOzKVrBYQdeogQEBjVK+su1SoyKUqRS9oQYOn3uNV9RQLG7UB1uzyrjgtyuCQCFLHDe1CTFRhQK2wNKD9xwxonkp2PgKlTiNlZ5THu5S7vb4GszWfIrAX2uibmxEVd7/dhE6asCJihWq3uBm2DgA=
  - secure: Jr7KCBUd3yGh1xm/Sym4VR4TWdTvzvy4J0IvucR14YPuesct+GjcBjfGlQHpv6IwPmXIKxky7hzdLbPM+fZK29xqtEJ66PnceTFM8GORTAJCLPU848UNmcYFsUzRgfJx9AmuDX26Q97AreBqY1YuwF7bCsyuzsaPeQrhjBeLuGzEcXGQz0iW+D+q1i0dYnHpV8nWH9OZr77t0H3DFpxS6Ej0QquvDa7LOPzgifQ2a8aaiyH8WAYvotOUlQALr+cFhA4ui1RXzdNX7yMHllAfcV0VxY3B02q0WBlYnSH/o5fpEuF9DEL0NwbMml5xEWlAF83Lp/YhP78htVIYqnXDQX3Nos0TlWG5ys6miQmkSLkNE1vq9U72iCWM2nwFLh1IpxZqsU6vjgLvtthj2i6pIJaZXNWYJUJwJmKTqf/2JT1MeplYkDCyxzZLjCHC9CXw8HOvA2Z0h7k/HYHJLYWXOI/93J+Ny2krmOoLA/cGhGN7nX48l9aCid3ptNuMK6qBjS1R00WCsg2j6dGfgvTRAdq7+NA67X4Drb4JgRx5rrPvppVRkdXw7zYl53lmrFlmERm8qAc9A00nGM1l/sLw/xuLPLirlIYf3qJWS9ieih/ajEgSQaHf8JAEOSdnwv5qVaW2ghlBgMlEp65CTIfRQBSEDIcksLnilF9X+nXwaMw=
script:
- ./sbt ++$TRAVIS_SCALA_VERSION test
- if [ "$TRAVIS_BRANCH" == "master" ]; then ./sbt ++$TRAVIS_SCALA_VERSION publish-signed;
  fi
notifications:
  email:
  - on_success: always
